package Theory;

public class Q5 {
	
//	What do you mean by Webservices, Explain the similarities and differences between a
//	Web application and Webservices.
	
//	---WS is also a type of WA, that can generate dynamic result as raw data(json, xml, text) 
//	instead of generating a html response (webpage)
//
//	--WA generates the view(webpage) whereas WS generates raw data.
//
//	--this raw data generated by the WS can be reused inside any other WA or any other type of application developed in any technology.
//
//	Indigo -----> html   (Webapplication) : it is for enduser
//	            -----> raw data (Webservices)  :- it is for any other application
//	Yatra 
//	 :----------Webapplication 
	
	
}
